"""Product Reel Director: from product photos to a professionally planned, beat-synced micro-shot Reel.

Pipeline: understand each photo -> concept -> micro-timeline (shots, camera, effects, transitions, text) -> render every
frame -> mux with the music. Nothing is generated by an AI video model: the product's own pixels are only cropped, scaled
and lit, so the product is never changed.
"""
